insert into `PUBLIC`.KEYWORD_ANALYTICS (keyword, search_count, create_at)
values ('키워드1', 0 , now()),
       ('키워드2', 1 , now()),
       ('키워드3', 2 , now()),
       ('키워드4', 3 , now()),
       ('키워드5', 4 , now()),
       ('키워드6', 5 , now()),
       ('키워드7', 6 , now()),
       ('키워드8', 7 , now()),
       ('키워드9', 8 , now()),
       ('키워드10', 9 , now()),
       ('키워드12', 10 , now()),
       ('키워드13', 11 , now()),
       ('키워드14', 12 , now()),
       ('키워드15', 13 , now()),
       ('키워드16', 14 , now());
